### ISSUE TITLE
Make change history collapsed by default

### ISSUE THREAD

**Issue by markwinter** [aptakube/kubespec.dev#5]
The first item of the ChangeList is set to default open. I think it would look cleaner and be easier to navigate if the first item was collapsed by default. The changes can be extremely long making the user have to scroll a lot. I think most users would be skipping over these change logs to see the Examples instead.

**Comment by goenning** [comment]
Yes, after using it for a while I have to agree that it’s becoming annoying :)

Would you like to send a PR?

**Comment by markwinter** [comment]
Hey, sure I can send one no problem
