### ISSUE TITLE
Mark which kinds are cluster-wide

### ISSUE THREAD

**Issue by stefanprodan** [aptakube/kubespec.dev#7]
It would be great to display `namespaced` or `cluster-wide` under each Kind. If you expand `metadata` it shows `namespace` on all kinds and this could confuse people.

**Comment by goenning** [comment]
Done! I've also marked the `namespace` field as required for namespaced resources, but I think it's best to keep this field visible on cluster scoped resources, it's part of the Schema after all, and the description is pretty clear that it's optional in some cases

![Screenshot 2024-12-17 at 14 21 11](https://github.com/user-attachments/assets/b82ddeff-fb54-4ed9-869c-7d20886cbac0)
