### ISSUE TITLE
Add an indicator to required fields

### ISSUE THREAD

**Issue by josh-hoiland** [aptakube/kubespec.dev#8]

**Comment by goenning** [comment]
Done! I'm actually surprised how few fields are actually required in most objects

**Comment by josh-hoiland** [comment]
I'm surprised too. I think the issue is that some fields are only conditionally required. For example, you'll get an error if you try to create a pod without a container image even though it's not marked as required, but the docs say: "This field is optional to allow higher level config management to default or override container images in workload controllers like Deployments and StatefulSets."

Really useful tool, btw. Thanks!
